name: Update plogonmaster

on:
  repository_dispatch:
    types: [new-release]

jobs:
  react:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Update plogonmaster.json
        shell: pwsh
        run: |
          $timestamp = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
          $apiLevel = ${{ github.event.client_payload.api_level }}
          $tag = '${{ github.event.client_payload.tag }}'
          $assetUrl = '${{ github.event.client_payload.asset_url }}'
          $path = './plogonmaster.json'

          $json = Get-Content $path | ConvertFrom-Json

          $json[0].LastUpdate = $timestamp

          if (!$${{ github.event.client_payload.is_testing }})
          {
            $json[0].DalamudApiLevel = $apiLevel
            $json[0].AssemblyVersion = $tag
            $json[0].DownloadLinkInstall = $assetUrl
            $json[0].DownloadLinkUpdate = $assetUrl
          }
          else
          {
            $json[0].TestingDalamudApiLevel = $apiLevel
            $json[0].TestingAssemblyVersion = $tag
            $json[0].DownloadLinkTesting = $assetUrl
          }

          $json | ConvertTo-Json -AsArray | Set-Content -Path $path
      - name: Commit plogonmaster.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plogonmaster.json
          git commit -m "ci: Update plogonmaster.json for ${{ github.event.client_payload.tag }}" || true
          git push
      